AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Metrics/ModuleLength:
  Max: 200

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UnreachableLoop:
  Exclude:
    - "spec/**/*"

Lint/EmptyBlock:
  Exclude:
    - "spec/**/*"

Layout/LineLength:
  Max: 120

Layout/BlockAlignment:
  Exclude:
    - "spec/**/*"
